limit_req_zone $binary_remote_addr zone=scratch_api:10m rate=10r/s;

resolver 127.0.0.11 ipv6=off valid=30s;
resolver_timeout 5s;

upstream cc_service {
  zone cc_service 64k;
  server cc-service:5000 resolve;
}

upstream bb_service {
  zone bb_service 64k;
  server warehouse-nginx:80 resolve;
}

server {
  listen 80;
  server_name scratch-app.hchch.tech;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass http://cc_service;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }
}

server {
  listen 80;
  server_name warehouse.hchch.tech;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass http://bb_service;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }
}
